# @package habitat.simulator.agents.fetch_suction
defaults:
  - agent_base
  - _self_
  - /habitat/simulator/sim_sensors@sim_sensors.head_rgb_sensor: head_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_depth_sensor: head_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.head_semantic_sensor: head_semantic_sensor

articulated_agent_type: DJIDrone
# articulated_agent_urdf: data/robots/dji_drone/urdf/dji_m100_sensors.urdf
articulated_agent_urdf: data/robots/dji_drone/urdf/dji_m100_sensors_scaled.urdf
# articulated_agent_urdf: data/robots/dji_drone/urdf/dji_m100_sensors_scaled_elevated.urdf