# @package habitat.task.actions
defaults:
  - /habitat/task/actions/arm_action@_here_
  - _self_


type: ArmPlaceAction
arm_controller: PixelArmAction
grip_controller: MagicGraspAction
grasp_thresh_dist: 0.15
render_ee_target: True
