# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
# type: RearrangeDataset-v0
split: val
data_path: data/datasets/objectnav/mp3d/v1/{split}/{split}.json.gz
scenes_dir: "data/scene_datasets/"
