# @package habitat.simulator.agents.fetch
defaults:
  - /habitat/simulator/agents/agent_base@_here_
  - _self_
  - /habitat/simulator/sim_sensors@sim_sensors.arm_rgb_sensor: arm_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_depth_sensor: arm_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_semantic_sensor: arm_semantic_sensor

radius: 0.3
articulated_agent_type: FetchRobot
articulated_agent_urdf: data/robots/hab_fetch/robots/hab_fetch.urdf
ik_arm_urdf: data/robots/hab_fetch/robots/fetch_onlyarm.urdf
