# @package habitat.simulator.agents.spot
defaults:
  - /habitat/simulator/agents/agent_base@_here_
  - _self_
  - /habitat/simulator/sim_sensors@sim_sensors.arm_rgb_sensor: arm_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_depth_sensor: arm_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_semantic_sensor: arm_semantic_sensor
radius: 0.25
height: 1.0
articulated_agent_type: "SpotRobot"
articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
ik_arm_urdf: "data/robots/hab_spot_arm/urdf/hab_spot_onlyarm_dae.urdf"
