defaults:
  - oracle_nav_action@_here_
  - _self_

type: OracleNavDiffBaseAction
motion_control: base_velocity # base_velocity_non_cylinder
lin_speed: 10.0
ang_speed: 10.0
spawn_max_dist_to_obj: -1.0
# For noncylinder navmesh action
# If we allow the agent to do sliding
allow_dyn_slide: True
# navmesh_offset: [[0.0, 0.0], [0.25, 0.0], [-0.25, 0.0]]
# navmesh_offset: [[0.0, 0.0], [0.0, 0.15], [0.0, -0.15]]
# If we allow the robot to move laterally
enable_lateral_move: False
# There is a collision if the difference between the clamped NavMesh position and target position
# is more than collision_threshold for any point.
collision_threshold: 1.0
dist_thresh: 0.5 # 0.3
turn_thresh: 0.1 # 0.5

# For re-computing navmesh for different bases 
base_type: "legged"
agent_height: 0.8
agent_radius: 0.0 # in fact = 0.05, can't navigate in mp3d navmesh if greater
agent_max_climb: 0.8  # 1.0 may be blocked into the ceiling, 0.5 too small to climb over obstacles
agent_max_slope: 90.0
