# @package habitat_baselines.rl.policy.hierarchical_policy.defined_skills
# See `oracle_skills.yaml` for details.

open_cab:
  skill_name: "NoopSkillPolicy"
  max_skill_steps: 1
  apply_postconds: True
  force_end_on_timeout: False
  pddl_action_names: ["open_cab_by_name"]

open_fridge:
  skill_name: "NoopSkillPolicy"
  max_skill_steps: 1
  apply_postconds: True
  force_end_on_timeout: False
  pddl_action_names: ["open_fridge_by_name"]

close_cab:
  skill_name: "NoopSkillPolicy"
  obs_skill_inputs: ["obj_start_sensor"]
  max_skill_steps: 1
  force_end_on_timeout: False
  pddl_action_names: ["close_cab_by_name"]

close_fridge:
  skill_name: "NoopSkillPolicy"
  obs_skill_inputs: ["obj_start_sensor"]
  max_skill_steps: 1
  apply_postconds: True
  force_end_on_timeout: False
  pddl_action_names: ["close_fridge_by_name"]

pick:
  skill_name: "OraclePickPolicy"
  action_name: "arm_pick_action"
  obs_skill_inputs: ["is_holding"]
  max_skill_steps: 1000
  apply_postconds: False
  force_end_on_timeout: False

pick_at_position:
  skill_name: "OraclePixelPickPolicy"
  action_name: "arm_pick_action"
  obs_skill_inputs: ["is_holding"]
  max_skill_steps: 200
  apply_postconds: False
  force_end_on_timeout: False

place:
  skill_name: "OraclePlacePolicy"
  action_name: "arm_place_action"
  obs_skill_inputs: []
  max_skill_steps: 100
  apply_postconds: True
  force_end_on_timeout: False

place_at_position:
  skill_name: "OraclePixelPlacePolicy"
  action_name: "arm_place_action"
  obs_skill_inputs: []
  max_skill_steps: 100
  apply_postconds: True
  force_end_on_timeout: False

wait:
  skill_name: "WaitSkillPolicy"
  action_name: "wait"
  obs_skill_inputs: []
  max_skill_steps: -1

nav_to_obj:
  skill_name: "OracleNavPolicy"
  # action_name: "base_velocity_non_cylinder"
  action_name: "base_velocity"
  obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
  max_skill_steps: 1000
  apply_postconds: False
  force_end_on_timeout: False
  obs_skill_input_dim: 3
  pddl_action_names: ["nav_to_obj", "nav_to_goal", "nav_to_receptacle_by_name"]


nav_to_position:
  skill_name: "OracleNavCoordPolicy"
  obs_skill_inputs: []
  max_skill_steps: 1000
  apply_postconds: False
  force_end_on_timeout: False
  obs_skill_input_dim: 3
  # We don't want to use this skill in the PDDL domain.
  # pddl_action_names: ["nav_to_position"]

reset_arm:
  skill_name: "ResetArmSkill"
  action_name: "arm_reset_action"
  obs_skill_inputs: []
  max_skill_steps: 100


turn_left:
  skill_name: "MoveSkillPolicy"
  force_end_on_timeout: False
  max_skill_steps: 1
  turn_power_y: 1.0
  apply_postconds: True

turn_right:
  skill_name: "MoveSkillPolicy"
  force_end_on_timeout: False
  max_skill_steps: 1
  turn_power_y: -1.0
  apply_postconds: True

move_forward:
  skill_name: "MoveSkillPolicy"
  force_end_on_timeout: False
  max_skill_steps: 1
  turn_power_x: 1.0
  apply_postconds: True

move_backward:
  skill_name: "MoveSkillPolicy"
  force_end_on_timeout: False
  max_skill_steps: 1
  turn_power_x: -1.0
  apply_postconds: True
