# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: eval
data_path: data/datasets/mp3d/mp3d_episodes.json.gz
scenes_dir: "data/scene_datasets/mp3d"