defaults:
- /benchmark/multi_agent: config_fetch_stretch_manipulation
- /habitat_baselines: habitat_baselines_rl_config_base
- /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
- /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.agent_0.obs_transforms.add_virtual_keys:
  - add_virtual_keys_base
- /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.agent_1.obs_transforms.add_virtual_keys:
  - add_virtual_keys_base
- /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_0: hl_fixed
- /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_1: hl_fixed
- ? /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.agent_0.hierarchical_policy.defined_skills
  : oracle_skills_multi_agent
- ? /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.agent_1.hierarchical_policy.defined_skills
  : oracle_skills_multi_agent
- /habitat/task/lab_sensors:
  - has_finished_oracle_nav
  - all_predicates
- _self_
habitat:
  dataset:
    data_path: data/datasets/sample/manipulation_eval_process_0.json.gz
habitat_baselines:
  distrib_updater_name: HRLDDPPO
  eval:
    episode_stored:
    - episode_id: 27
      sample_frame:
      - - 1
        - 0
      - - 1
        - 1
      - - 21
        - 0
      - - 21
        - 1
      - - 41
        - 0
      - - 41
        - 1
      - - 43
        - 0
      - - 43
        - 1
      - - 55
        - 0
      - - 55
        - 1
      - - 145
        - 0
      - - 145
        - 1
      - - 157
        - 0
      - - 157
        - 1
      - - 165
        - 0
      - - 165
        - 1
      - - 177
        - 0
      - - 177
        - 1
      - - 185
        - 0
      - - 185
        - 1
      - - 197
        - 0
      - - 197
        - 1
      - - 205
        - 0
      - - 205
        - 1
      - - 217
        - 0
      - - 217
        - 1
      - - 225
        - 0
      - - 225
        - 1
      - - 237
        - 0
      - - 237
        - 1
      - - 245
        - 0
      - - 245
        - 1
      - - 257
        - 0
      - - 257
        - 1
      - - 265
        - 0
      - - 265
        - 1
      - - 277
        - 0
      - - 277
        - 1
      - - 280
        - 0
      - - 280
        - 1
    - episode_id: 64
      sample_frame:
      - - 1
        - 0
      - - 1
        - 1
      - - 21
        - 0
      - - 21
        - 1
      - - 41
        - 0
      - - 41
        - 1
      - - 61
        - 0
      - - 61
        - 1
      - - 81
        - 0
      - - 81
        - 1
      - - 87
        - 0
      - - 87
        - 1
      - - 101
        - 0
      - - 101
        - 1
      - - 121
        - 0
      - - 121
        - 1
      - - 140
        - 0
      - - 140
        - 1
      - - 189
        - 0
      - - 189
        - 1
      - - 209
        - 0
      - - 209
        - 1
      - - 229
        - 0
      - - 229
        - 1
      - - 242
        - 0
      - - 242
        - 1
      - - 249
        - 0
      - - 249
        - 1
      - - 262
        - 0
      - - 262
        - 1
      - - 269
        - 0
      - - 269
        - 1
      - - 282
        - 0
      - - 282
        - 1
      - - 289
        - 0
      - - 289
        - 1
      - - 302
        - 0
      - - 302
        - 1
      - - 309
        - 0
      - - 309
        - 1
      - - 322
        - 0
      - - 322
        - 1
      - - 329
        - 0
      - - 329
        - 1
      - - 342
        - 0
      - - 342
        - 1
      - - 349
        - 0
      - - 349
        - 1
      - - 362
        - 0
      - - 362
        - 1
      - - 360
        - 0
      - - 360
        - 1
    - episode_id: 102
      sample_frame:
      - - 1
        - 0
      - - 1
        - 1
      - - 21
        - 0
      - - 21
        - 1
      - - 38
        - 0
      - - 38
        - 1
      - - 41
        - 0
      - - 41
        - 1
      - - 61
        - 0
      - - 61
        - 1
      - - 81
        - 0
      - - 81
        - 1
      - - 101
        - 0
      - - 101
        - 1
      - - 121
        - 0
      - - 121
        - 1
      - - 140
        - 0
      - - 140
        - 1
      - - 141
        - 0
      - - 141
        - 1
      - - 160
        - 0
      - - 160
        - 1
      - - 161
        - 0
      - - 161
        - 1
      - - 180
        - 0
      - - 180
        - 1
      - - 181
        - 0
      - - 181
        - 1
      - - 200
        - 0
      - - 200
        - 1
      - - 201
        - 0
      - - 201
        - 1
      - - 209
        - 0
      - - 209
        - 1
      - - 220
        - 0
      - - 220
        - 1
      - - 240
        - 0
      - - 240
        - 1
      - - 260
        - 0
      - - 260
        - 1
      - - 280
        - 0
      - - 280
        - 1
      - - 300
        - 0
      - - 300
        - 1
      - - 311
        - 0
      - - 311
        - 1
      - - 320
        - 0
      - - 320
        - 1
      - - 331
        - 0
      - - 331
        - 1
      - - 340
        - 0
      - - 340
        - 1
      - - 351
        - 0
      - - 351
        - 1
      - - 360
        - 0
      - - 360
        - 1
      - - 371
        - 0
      - - 371
        - 1
      - - 380
        - 0
      - - 380
        - 1
      - - 391
        - 0
      - - 391
        - 1
      - - 391
        - 0
      - - 391
        - 1
    - episode_id: 136
      sample_frame:
      - - 1
        - 0
      - - 1
        - 1
      - - 21
        - 0
      - - 21
        - 1
      - - 41
        - 0
      - - 41
        - 1
      - - 61
        - 0
      - - 61
        - 1
      - - 81
        - 0
      - - 81
        - 1
      - - 86
        - 0
      - - 86
        - 1
      - - 97
        - 0
      - - 97
        - 1
      - - 188
        - 0
      - - 188
        - 1
      - - 199
        - 0
      - - 199
        - 1
      - - 208
        - 0
      - - 208
        - 1
      - - 219
        - 0
      - - 219
        - 1
      - - 228
        - 0
      - - 228
        - 1
      - - 239
        - 0
      - - 239
        - 1
      - - 248
        - 0
      - - 248
        - 1
      - - 259
        - 0
      - - 259
        - 1
      - - 268
        - 0
      - - 268
        - 1
      - - 279
        - 0
      - - 279
        - 1
      - - 288
        - 0
      - - 288
        - 1
      - - 299
        - 0
      - - 299
        - 1
      - - 308
        - 0
      - - 308
        - 1
      - - 319
        - 0
      - - 319
        - 1
      - - 328
        - 0
      - - 328
        - 1
      - - 334
        - 0
      - - 334
        - 1
    image_option:
    - disk
    json_option: []
    should_load_ckpt: false
    video_option:
    - disk
    video_option_new: false
  eval_keys_to_include_in_name:
  - pddl_success
  evaluate: true
  evaluator:
    _target_: habitat_baselines.rl.multi_agent.habitat_mas_evaluator.HabitatMASEvaluator
  force_torch_single_threaded: true
  image_dir: video_dir/image_dir/
  load_resume_state_config: false
  log_interval: 1
  num_checkpoints: 10
  num_environments: 1
  num_updates: -1
  rl:
    agent:
      agent_sample_interval: 20
      force_partner_sample_idx: -1
      num_active_agents_per_type:
      - 1
      - 1
      num_agent_types: 2
      num_pool_agents_per_type:
      - 1
      - 1
      type: MultiAgentAccessMgr
      use_llm_agent: true
    ddppo:
      backbone: resnet18
      distrib_backend: NCCL
      num_recurrent_layers: 2
      pretrained: false
      pretrained_encoder: false
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      reset_critic: false
      rnn_type: LSTM
      sync_frac: 0.6
      train_encoder: true
    policy:
      agent_0:
        hierarchical_policy:
          defined_skills:
            nav_to_obj:
              action_name: base_velocity
              max_skill_steps: 1500
              obs_skill_inputs:
              - obj_start_sensor
              - abs_obj_start_sensor
              - obj_goal_sensor
              - abs_obj_goal_sensor
              skill_name: OracleNavPolicy
            pick:
              action_name: arm_action
              max_skill_steps: 100
              obs_skill_inputs:
              - is_holding
              skill_name: OraclePickPolicy
          high_level_policy:
            add_arm_rest: false
            allowed_actions:
            - wait
            - nav_to_goal
            - nav_to_obj
            - nav_to_goal_dog
            - pick
            - place
            - nav_to_receptacle_by_name
            policy_input_keys:
            - articulated_agent_arm_rgb
            - articulated_agent_arm_depth
            - is_holding
            - obj_start_gps_compass
            - obj_goal_gps_compass
            - other_agent_gps
            - obj_start_sensor
            - obj_goal_sensor
            - all_predicates
            termination_obs_name: agents_within_threshold
          ignore_skills:
          - open_cab
          - open_fridge
          - close_cab
          - close_fridge
      agent_1:
        hierarchical_policy:
          defined_skills:
            nav_to_obj:
              action_name: base_velocity
              max_skill_steps: 1500
              obs_skill_inputs:
              - obj_start_sensor
              - abs_obj_start_sensor
              - obj_goal_sensor
              - abs_obj_goal_sensor
              skill_name: OracleNavPolicy
            pick:
              action_name: arm_action
              max_skill_steps: 100
              obs_skill_inputs:
              - is_holding
              skill_name: OraclePickPolicy
          high_level_policy:
            add_arm_rest: false
            allowed_actions:
            - wait
            - nav_to_goal
            - nav_to_obj
            - nav_to_goal_dog
            - pick
            - place
            - nav_to_receptacle_by_name
            policy_input_keys:
            - articulated_agent_arm_rgb
            - articulated_agent_arm_depth
            - is_holding
            - obj_start_gps_compass
            - obj_goal_gps_compass
            - other_agent_gps
            - obj_start_sensor
            - obj_goal_sensor
            - all_predicates
            termination_obs_name: agents_within_threshold
          ignore_skills:
          - open_cab
          - open_fridge
          - close_cab
          - close_fridge
    ppo:
      clip_param: 0.2
      entropy_coef: 0.0001
      eps: 1e-5
      gamma: 0.99
      lr: 0.00025
      max_grad_norm: 0.2
      num_mini_batch: 2
      num_steps: 128
      ppo_epoch: 1
      tau: 0.95
      use_gae: true
      value_loss_coef: 0.5
  rollout_storage_name: HrlRolloutStorage
  torch_gpu_id: 0
  total_num_steps: 1e8
  trainer_name: ddppo
  updater_name: HRLPPO
  verbose: false
  video_dir: video_dir/manipulation_new
  video_fps: 30
