name: "HierarchicalPolicy"
obs_transforms:
  add_virtual_keys:
    virtual_keys:
      "goal_to_agent_gps_compass": 2
hierarchical_policy:
  high_level_policy:
    name: "LLMHighLevelPolicy"
    # Timeout condition for the planning algorithm.
    max_search_depth: 8
    plan_idx: 1
    # Whether to randomly sample one of the plans, or always go with one of the plans indexed by `plan_idx`
    allow_other_place: False
  defined_skills: {}
