objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: any_targets|2
    expr_type: movable_entity_type
  - name: any_targets|3
    expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  - name: TARGET_any_targets|1
    expr_type: goal_entity_type
  - name: TARGET_any_targets|2
    expr_type: goal_entity_type
  - name: TARGET_any_targets|3
    expr_type: goal_entity_type
  - name: agent_0
    expr_type: robot_entity_type
  - name: agent_1
    expr_type: robot_entity_type
  - name: agent_2
    expr_type: robot_entity_type
  - name: agent_3
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - robot_at(TARGET_any_targets|1, agent_1)
    - robot_at(TARGET_any_targets|3, agent_3)
    - at(any_targets|0, TARGET_any_targets|0)
    - at(any_targets|2, TARGET_any_targets|2)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, agent_0)
      - robot_at(any_targets|1, agent_1)
      - robot_at(any_targets|2, agent_2)
      - robot_at(any_targets|3, agent_3)
  stage_2:
    expr_type: AND
    sub_exprs:
      - holding(any_targets|0, agent_0)
      - holding(any_targets|2, agent_2)
  stage_3:
    expr_type: AND
    sub_exprs:
      - at(any_targets|0, TARGET_any_targets|0)
      - at(any_targets|2, TARGET_any_targets|2)

solution:
  - nav_to_goal(any_targets|0, agent_0)
  - nav_to_goal(any_targets|1, agent_1)
  - nav_to_goal(any_targets|2, agent_2)
  - nav_to_goal(any_targets|3, agent_3)
  - pick(any_targets|0, agent_0)
  - nav_to_obj(TARGET_any_targets|0, agent_0)
  - place(any_targets|0,TARGET_any_targets|0, agent_0)
  - pick(any_targets|2, agent_2)
  - nav_to_obj(TARGET_any_targets|2, agent_2)
  - place(any_targets|2,TARGET_any_targets|2, agent_2)
