# Since two objects are both far beyond stretch's reach
# The oracle solution should be assigning fetch to rearrange both objects.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  # - name: any_targets|1
  #   expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  # - name: TARGET_any_targets|1
  #   expr_type: goal_entity_type
  - name: agent_0
    expr_type: robot_entity_type
  - name: agent_1
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - at(any_targets|0, TARGET_any_targets|0)
    # - at(any_targets|1, TARGET_any_targets|1)
    # - not_holding(agent_0)
    # - not_holding(agent_1)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, agent_0)
  stage_2:
    expr_type: AND
    sub_exprs:
      - holding(any_targets|0, agent_0)
  stage_3:
    expr_type: AND
    sub_exprs:
      - at(any_targets|0, TARGET_any_targets|0)
  # stage_4:
  #   expr_type: AND
  #   sub_exprs:
  #     - robot_at(any_targets|1, agent_0)
  # stage_5:
  #   expr_type: AND
  #   sub_exprs:
  #     - holding(any_targets|1, agent_0)
  # stage_6:
  #   expr_type: AND
  #   sub_exprs:
  #     - at(any_targets|1, TARGET_any_targets|1)

solution:
  - reset_arm(agent_0)
  - nav_to_obj(any_targets|0, agent_0)
  # - pick(any_targets|1, robot_0)
  - pick(any_targets|0, agent_0)
  - reset_arm(agent_0)
  - nav_to_obj(TARGET_any_targets|0, agent_0)
  # - nav_to_obj(TARGET_any_targets|0, robot_1)
  - place(any_targets|0,TARGET_any_targets|0, agent_0)
  - reset_arm(agent_0)
  # - nav_to_goal(any_targets|1, agent_0)
  # - pick(any_targets|1, agent_0)
  # - nav_to_obj(TARGET_any_targets|1, agent_0)
  # - place(any_targets|1, TARGET_any_targets|1, agent_0)
