# The rearrangement task with robot_1 perceives the target object first.
# Make sure the robot_0 is spot and the robot_1 is drone.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: any_targets|2
    expr_type: movable_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - robot_at(any_targets|2, robot_0)
    - robot_at(any_targets|2, robot_1)
    - holding(any_targets|0, robot_0)
    - holding(any_targets|1, robot_1)

stage_goals:
  stage_1:
    expr_type: OR
    sub_exprs:
      - robot_at(any_targets|2, robot_0)
      - robot_at(any_targets|2, robot_1)
  stage_2:
    expr_type: OR
    sub_exprs:
      - holding(any_targets|0, robot_0)
      - holding(any_targets|1, robot_1)

solution:
  # - nav_to_goal(any_targets|1, robot_0)
  # - nav_to_goal(any_targets|0, robot_1)
  # - pick(any_targets|1, robot_0)
  # - pick(any_targets|0, robot_1)
  - nav_to_goal(any_targets|0, robot_0)
  - nav_to_goal(any_targets|1, robot_1)
  - pick(any_targets|0, robot_0)
  - pick(any_targets|1, robot_1)
  - nav_to_goal(any_targets|2, robot_0)
  - nav_to_goal(any_targets|2, robot_1)